### ISSUE TITLE
My Local PC(M1 macOs) not working.

### ISSUE THREAD

**Issue by umyonghyun** [criteo/JVips#136]
hello. 
i used to macOS by M1. 
so i test this library but not working as a blew message please check my issue. 
and i wonder that this issue is releated to m1.

`java.lang.UnsatisfiedLinkError: /private/var/folders/x7/xxt_f2hd4z7bn25xsr8h88km0000gp/T/libJVips.dylib7088253940309062473: dlopen(/private/var/folders/x7/xxt_f2hd4z7bn25xsr8h88km0000gp/T/libJVips.dylib7088253940309062473, 0x0001): Library not loaded: /usr/local/opt/glib/lib/libglib-2.0.0.dylib
  Referenced from: /private/var/folders/x7/xxt_f2hd4z7bn25xsr8h88km0000gp/T/libJVips.dylib7088253940309062473
  Reason: tried: '/usr/local/opt/glib/lib/libglib-2.0.0.dylib' (no such file), '/usr/lib/libglib-2.0.0.dylib' (no such file)
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1837)
	at com.criteo.vips.Vips.loadLibraryFromJar(Vips.java:112)
	at com.criteo.vips.Vips.<clinit>(Vips.java:63)`

**Comment by dbouron** [comment]
Hi,
libJVips.dylib hasn't been compiled for arm architecture but only for x86_64. This is why you have this error

**Comment by kdekooter** [comment]
Is there a way to work around this? Or is a compilation for ARM on the roadmap?

**Comment by esiqveland** [comment]
Did you solve this?

**Comment by kdekooter** [comment]
bump
