### ISSUE TITLE
libtiff.so not loaded from jar

### ISSUE THREAD

**Issue by pclewis** [criteo/JVips#140]
Looks like tiff is meant to be in LINUX_LIBRARIES somewhere between jpeg and vips.

**Comment by weltonrodrigo** [comment]
I belive the problem here is that libvips inside the jar depends on libtiff:

```java
Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/libvips.so9627007704616512387: libtiff.so.5: cannot open shared object file: No such file or directory
        at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
        at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:331)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:197)
        at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:139)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2418)
        at java.base/java.lang.Runtime.load0(Runtime.java:852)
        at java.base/java.lang.System.load(System.java:2025)
        at com.criteo.vips.Vips.loadLibraryFromJar(Vips.java:112)
        at com.criteo.vips.Vips.tryLoadLibrariesFromJar(Vips.java:78)
        at com.criteo.vips.Vips.<clinit>(Vips.java:58)
        at Vips.main(foo.java:10)
```
