### ISSUE TITLE
Getting UnsatisfiedLinkError in amd64 Docker image

### ISSUE THREAD

**Issue by mykola-mokhnach** [criteo/JVips#146]
Hello,

I am trying to use JVips in a java code, which is executed in a Docker image built for amd64 architecture. Unfortunately the execution always fails with the following error:

```
java.lang.UnsatisfiedLinkError: /tmp/libimagequant.so2816613226528914785: libgomp.so.1: cannot open shared object file: No such file or directory
	at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
	at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2450)
	at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2506)
	at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2705)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2635)
	at java.base/java.lang.Runtime.load0(Runtime.java:768)
	at java.base/java.lang.System.load(System.java:1850)
	at com.criteo.vips.Vips.loadLibraryFromJar(Vips.java:112)
	at com.criteo.vips.Vips.tryLoadLibrariesFromJar(Vips.java:78)
	at com.criteo.vips.Vips.<clinit>(Vips.java:58)
	at com.scripting.ImageUtils.convertToPng(ImageUtils.java:9)
```

I believe I have included the necessary libs into the base image

```
FROM ubuntu:22.04 AS base
...
RUN apt-get update -qq \
    && apt-get install -qq \
    openjdk-11-jdk \
    libvips42 \
    libgomp1
```

The lib version used:

```
      <dependency>
        <groupId>com.criteo</groupId>
        <artifactId>jvips</artifactId>
        <version>8.12.2-69bf715</version>
      </dependency>
```

Code example:

```
public class ImageUtils {
	public static byte[] convertToPng(byte[] imageBytes, boolean autorotate) {
		try (var image = new VipsImage(imageBytes, imageBytes.length)) {
			if (autorotate) {
				try {
					image.autorot();
				} catch (VipsException ignore) {}
			}
			return image.writeToArray(VipsImageFormat.PNG, false);
		}
	}
}
```

**Comment by mykola-mokhnach** [comment]
Seems like it was an issue with my image, however this also means libgomp.so is not included into the Maven jar.
