### ISSUE TITLE
Throwing error while trying to resize tiff image on amazon linux 2

### ISSUE THREAD

**Issue by titas-biswas-bazaarvoice** [criteo/JVips#60]
Though it seems bit strange, but, It is working fine while running on mac osx but throwing an exception while trying to **resize heic/tiff/bmp/pdf**, `com.criteo.vips.VipsException: Unable to decode image buffer` when deployed in **Amazon Linux 2** Instances ( both EC2 and local docker container).
JPG/PNG/GIF is working fine in mas os x as well as Amazon Linux 2 Instances

The resizing code:
```
public byte[] scaleKeepingAspectRatio(int maxDim, byte[] imageData, boolean stripMeta) {
        VipsImage image = null;
        byte[] outData = null;
        try {
            image = new VipsImage(imageData, imageData.length);
            image = scale(image, maxDim, maxDim, false);
            outData = image.writeToArray(VipsImageFormat.JPG, stripMeta);
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            image.release();
        }
        return outData;
    }

    private VipsImage scale(VipsImage image, int width, int height, boolean forceScale) {
        Dimension destDimension = new Dimension(width, height);
        image.resize(destDimension, forceScale);
        return image;
    }
```

The test code:
```
static String in_path = "/mnt/sample.tiff";
    static String out_path = "/mnt/sample_out.jpg";

    public static void testSimple() {
        // Set vips memory leak report at exit
        VipsContext.setLeak(true);
        VipsImage image = null;
        VipsImage metaStripedImage = null;
        String fileSeparator = FileSystems.getDefault().getSeparator();
        try {
            byte[] contents = VipsTestUtils.readFromFile(in_path);
           VipsImageProcessor processor = new VipsImageProcessor();
           byte[] outContents = processor.scaleKeepingAspectRatio(900, contents, false);

            System.out.println(contents.length);
            VipsTestUtils.writeToFile(out_path, outContents);

        } catch (IOException | VipsException e) {
            e.printStackTrace();
        }
    }
```
The utils code
```
   public static void writeToFile(String outputFilePath, byte[] bytes) throws IOException {
        Path path = Paths.get(outputFilePath);
        Files.deleteIfExists(path);
        Files.createFile(path);
        Files.write(path, bytes);
    }

    public static byte[] readFromFile(String inputFilePath) throws IOException {
        Path path = Paths.get(inputFilePath);
        return Files.readAllBytes(path);
    }
```

The Exception:

```
com.criteo.vips.VipsException: Unable to decode image buffer
	at com.criteo.vips.VipsImage.newFromBuffer(Native Method)
	at com.criteo.vips.VipsImage.<init>(VipsImage.java:53)
	at pvt.titas.vips.service.impl.VipsImageProcessor.scaleKeepingAspectRatio(VipsImageProcessor.java:19)
...
...
1 objects alive:
0) VipsSource (0x7f58c4ffe800), count=1
VipsSource (source), input source, 
1 VipsArea alive
	0x7f58c4fb46f0 count = 1, bytes = 5233994
memory: 1 allocations, 5234010 bytes
files: 0 open
memory: high-water mark 4.99 MB
error buffer: VipsForeignLoad: source is not in a known format
VipsForeignLoad: buffer is not in a known format
```

The test project is https://gitlab.com/titasbiswas/java/references/spring/vips-primer

**Comment by dbouron** [comment]
Hello,
yes this is normal because for MacOS platform we build JVips from the vips package in brew. This one has all libvips dependencies (PDFium, libtiff, etc). For Windows and Linux platform, we build dependecies from source and for the moment these formats aren't surpported since we didn't add the required dependencies.
